### ISSUE TITLE
enable change grid/list/thumb view in php/mysql

### ISSUE THREAD

**Issue by yan777** [1rosehip/jplist#1]
is it possible to add the list-grid-view in php-mysql version?  
http://jplist.com/datasourcesexamples/php-mysql-demo 

so i can modify easily thx.
solved.just change the jplist css and js file

**Comment by ZeynepP** [comment]
Sqlite demo seems not working. I also tried the source code, same result. 
https://jplist.com/datasourcesexamples/php-sqlite-demo 

FYI,
Bests
