### ISSUE TITLE
Data Sources Handlebars - Counter Control & Button Text Filter Control

### ISSUE THREAD

**Issue by Extracreative** [1rosehip/jplist#104]
How do I use Counter Control & Button Text Filter Control with Jplist Data Sources Handlebars?
What controls file do I add the buttons & counter details to?

**Comment by Extracreative** [comment]
is this possible?

**Comment by no81no** [comment]
Sorry for the late response.
Unfortunately this controls are still not implemented in data sources including mysql.
I'm going to add all controls there, but I still have no estimation time for that.

**Comment by Extracreative** [comment]
Has development stopped on jplist?

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#2

**Comment by Extracreative** [comment]
please reopen

**Comment by no81no** [comment]
Button text filter control is added:
https://github.com/no81no/jplist/blob/master/demo/php-mysql-demos/10-button-text-filter.html
https://github.com/no81no/jplist/blob/master/server/controls/button-text-filter.php
