### ISSUE TITLE
Active Filters

### ISSUE THREAD

**Issue by Isquaretech** [1rosehip/jplist#12]
Hello ,
How can i show the all the filters applied to the data in jplist .to a particular div inside panel.
Is  there any data-attribute to fetch which is active currently in jplist.

For example i.e i
![screenshot_2](https://cloud.githubusercontent.com/assets/8542450/4026922/e24f86a2-2c24-11e4-8ad2-db5a7af01073.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/8542450/4026923/e815fbe8-2c24-11e4-81bd-b9e4836fc7e3.png).

Hoping for a positive response.

Regards 
iSqaure

**Comment by shaliniseb** [comment]
how can i find out which filter is selected on redrawCallback?
