### ISSUE TITLE
Pagination and results disappear when filter is applied after you click the pagination buttons

### ISSUE THREAD

**Issue by taylormade313** [1rosehip/jplist#229]
I have a filter that filters on a date. When I select the year I want for the filter it shows the results, currently I have the resuts set to show 10 per page. The results show for example view 1-10 of 70. When I click any of the pagination buttons to see the next set of 10 the results disapper and so does the pagination area. I'm not sure why this is happening.

**Comment by no81no** [comment]
Please follow [jPList guidelines](https://github.com/no81no/jplist/wiki/Reporting-issues) for opening issues and use jsFiddle, jsBin, or other such service to share your test case.
