### ISSUE TITLE
Feature Req: customize pagination for  <<    <     >    >>  for the visually impaired

### ISSUE THREAD

**Issue by BDDinh** [1rosehip/jplist#230]
The Google style pagination has   <<    <     >    >>   to move through the pages.

But for the visually impaired people who rely on html translators, they can only hear "Less-than sign Less-than sign" "Less-than sign"  "More-than sign" More-than sign More-than sign" instead of "Go to first page" "Go back to previous page" "Go back to next page" Go back to last page".

It would be great if you can provide a way to customize the following:
"<<" to an img tag that has an alt "Go to first page" value
"<"   to an img tag that has an alt "Go to previous page" value

">"    to an img tag that has an alt "Go to next page" value
">>"  to an img tag that has an alt "Go to last page" value

**Comment by 1rosehip** [comment]
The feature is implemented.
Please download the following js file:
https://raw.githubusercontent.com/1rosehip/jplist/master/dist/js/jplist.pagination-bundle.min.js

Usage example:
```
<div
                        class="jplist-pagination"
                        data-control-type="pagination"
                        data-control-name="paging"
                        data-control-action="paging"
                        data-items-per-page="5"
                        data-prev="<"
                        data-prev-title="Prev"
                        data-next=">"
                        data-next-title="Next"
                        data-first="<<"
                        data-first-title="First"
                        data-last=">>"
                        data-last-title="Last"
                        data-number-title="Go to the page #{number}">
                </div>
```

**Comment by BDDinh** [comment]
Thank you so much!

And have a **great** day!!

**Comment by 1rosehip** [comment]
You are welcome!
