### ISSUE TITLE
Missing the autocomplete feature on Github and website

### ISSUE THREAD

**Issue by superfoght** [1rosehip/jplist#232]
The JS and CSS files for the autocomplete feature (http://jplist.com/controls/autocomplete ) is missing from both the website and github

**Comment by superfoght** [comment]
I had the files sent to me by mail, and have tested them out. It doesn't seem that they work with the current version of jplist.core.js  - or maybe I'm doing something wrong ;-)

**Comment by thleh** [comment]
I would like to use that feature too. Can you please publish the missing libary :-)

**Comment by 1rosehip** [comment]
Autocomplete control is added here (client side version only for now):
https://raw.githubusercontent.com/1rosehip/jplist/master/dist/js/jplist.autocomplete.min.js
https://raw.githubusercontent.com/1rosehip/jplist/master/dist/css/jplist.autocomplete.min.css

Please also download the latest core:
https://raw.githubusercontent.com/1rosehip/jplist/master/dist/js/jplist.core.min.js

Demo page:
https://github.com/1rosehip/jplist/blob/master/demo/16-autocomplete.html

**Comment by superfoght** [comment]
Works great. Thanks for the help :) 

Should I close the issue?

**Comment by 1rosehip** [comment]
Yes, please
