### ISSUE TITLE
Issue within jplist.core-ajax.min.js - Version 5.2.0.10

### ISSUE THREAD

**Issue by thleh** [1rosehip/jplist#233]
When using jplist with other jQuery components and one of them use jQuery.noconflict() there is an issue within jplist.core-ajax.min.js.

Please fix line 542 and use jQuery instead of $:

 $.each(b.data(), function(c, e) {                     should be changed to
 jQuery.each(b.data(), function(c, e) {

**Comment by 1rosehip** [comment]
Thank you for reporting this issue.
It's fixed in both jplist.core-ajax.min.js and jplist.core.min.js now.
