### ISSUE TITLE
Number sorting is not working right above

### ISSUE THREAD

**Issue by RvWensen** [1rosehip/jplist#234]
Hi,

If you have numbers below and above 1000 thinks go wrong.
Exmaple: http://www.awesomescreenshot.com/image/1813022/3626a8b08242f33f3556f0b59fbb2d91

Kind regards,

**Comment by 1rosehip** [comment]
Hi,
I see that this is a jplist website screenshot.
Have you just changed like values in firebug / chrome developer toolbar?
If so it won't work this way.
jPList collects data on page load and 'remembers' the values of each DOM element.
This values can be changed only through jPList API: http://jplist.com/documentation/api-add-one-item

Thanks

**Comment by RvWensen** [comment]
Hi,

I made that to show my error as easy as possible.
But i also have the error on my live site.

So the bug is real, could you test it your self please? :-)

Kind regards,

Roy

**Comment by 1rosehip** [comment]
Hi,
Unfortunately I can't reproduce the error,
that's why I'm always asking for a live demo.

Best regards

**Comment by RvWensen** [comment]
Hi,

Oke then here the life site. ( https://www.creditcard.nl/aanvragen )
If you sort on 'bestedingslimiet' its going wrong.

>> http://www.awesomescreenshot.com/image/1872110/b6af1376f4f59098fed90925e2c9dc66

Kind regards,

Roy

**Comment by 1rosehip** [comment]
The issue on your website that you prices have a decimal point (.) inside your numbers. Thereby 500 > 20.000

You have 2 possible solutions for this issue:
- you may use 20,000.00 instead of 20.000,00
- or use can create a hidden field that contains only 20000 like values without the dot and then sort by this field.

Best regards

**Comment by RvWensen** [comment]
Hi, 

I am sorry for not testing that one.
Tnx for your help!

Kind regards,

Roy
