### ISSUE TITLE
Desc sort button do not work

### ISSUE THREAD

**Issue by cdupland** [1rosehip/jplist#238]
Hi,

I am using the control buttons to sort my list. I have 4 sortable path all with number type.
When I check the result sort after click, I note that the desc sort is not working well.
I am using a basic structure like it's show in the documentation.

How can I resolve this problem ?

Thanks

**Comment by 1rosehip** [comment]
Hi, 
Please create reproducible test case with jsFiddle, jsBin, Codepen or other similar service to share your test case.

Thanks
