### ISSUE TITLE
Pagination can support the jump to the input page?

### ISSUE THREAD

**Issue by xuanskyer** [1rosehip/jplist#240]
Pagination can support the jump to the input page?

**Comment by 1rosehip** [comment]
What do you mean by input page?

**Comment by xuanskyer** [comment]
@1rosehip 

sorry, I don't have a clear statement,like this:

![page](https://github.com/xuanskyer/public/blob/master/110002_iLjL_914061.png.jpg?raw=true)

**Comment by xuanskyer** [comment]
I changed the old version jplist.bootstrap-pagination-bundle.min.js.

* add a text input box 

```
<input name="" vlaue="" type="text" style="margin:10px;width:80px;" placeholder="jump to.."  class="jplist-jump-dest" />
```
* then bind keypress enter:

```
//input page jump js
    jQuery(document).on('keypress', '.jplist-jump-dest', function(event){
        if(13 == event.which){
            var page_num = Number(jQuery(this).val() - 1) || 0;
            jQuery('.jplist-pagesbox').append('<button type="button" style="display: none;" data-type="page" data-number="'+page_num+'">'+page_num+'</button>');
            jQuery.each(jQuery('button[data-number='+page_num+']'),  function(){
                jQuery(this).click();return false;
            });
        }
    });
```

like this:
![changed code](https://github.com/xuanskyer/public/blob/master/53554.png?raw=true)

ugly code , but it works! :)

**Comment by 1rosehip** [comment]
I'm glad that it works! 👍
