### ISSUE TITLE
Can controls be only buttons?

### ISSUE THREAD

**Issue by happy2deepak** [1rosehip/jplist#247]
Really liked the plugin and have implemented the same in my design. But there's a specific requirement in my project, where the controls are plain buttons kept inline. (i.e. No Dropdown, No input, No Toggle, No slider). How can I achieve this ?

![image](https://cloud.githubusercontent.com/assets/1978524/21761000/321e951c-d676-11e6-87ce-56fd653a53da.png)

I require to develop somthing like this, but without the toggle feature. (I used this controls, but it requires the user to click again and toggle back the selected filter control)

![filters](https://cloud.githubusercontent.com/assets/1978524/21761030/5d4f87e6-d676-11e6-8872-f745a1e66d0e.png)

This is my snapshot. It has a Tab like layout, instead of showing and hiding, it filters the content as per category.

**Comment by 1rosehip** [comment]
You may use http://jplist.com/documentation/control-settings/button-filters-group with data-mode="single"

It works like radio buttons and allows that only one button will be selected at a time without 'toggle'
