### ISSUE TITLE
Is there someplace that documents the statuses field?

### ISSUE THREAD

**Issue by jas0995** [1rosehip/jplist#248]
Hi, Great library!!  I like it a lot.  I now have a need to be able to show records from a data source of over 250,000 records. 

I am trying to use the php server functionality and I am having a hard time sorting out the call to the server.

I looked over the server code, and it is broken into so many pieces I am having trouble sorting out the code.  Is there some documentation somewhere that documents the statuses field?

Is there any way to just have jquery pass a json array of current sort/filter/etc options to the server?

Thanks
-John

**Comment by 1rosehip** [comment]
Unfortunately there is no a general documentation about control statuses in PHP.
But every PHP control has a comment that describes status structure and its fields.
Also you may look into the network tab in the browser console to see the whole statuses passed from the client to the server side.
