### ISSUE TITLE
PHP and MySQL Data Source

### ISSUE THREAD

**Issue by renanarozen** [1rosehip/jplist#260]
Hi,
[phptest.txt](https://github.com/1rosehip/jplist/files/933591/phptest.txt)

I'm using php and MySql data source.
I succeeded to see the items but the pagination controller is not working

Glade for your help
Renana

**Comment by 1rosehip** [comment]
Hi,
Please check you php log to see if there any errors related to jplist or pagination control.
Also please follow [ jPList guidelines](https://github.com/1rosehip/jplist/wiki/Reporting-issues) for opening issues.

Best regards

**Comment by renanarozen** [comment]
Hi i can't see any error in my php log
Look at the file i that attache it looks like he start pagination but hide it
[jplist_p.pptx](https://github.com/1rosehip/jplist/files/940962/jplist_p.pptx)

Thanks

**Comment by htemplates** [comment]
Please check you console network tab and paste response of the appropriate php file (server-html.php or server-json.php)

**Comment by 1rosehip** [comment]
Please check you console network tab and paste response of the appropriate php file (server-html.php or server-json.php)

**Comment by renanarozen** [comment]
It's server-json.php
[data.txt](https://github.com/1rosehip/jplist/files/943235/data.txt)

**Comment by renanarozen** [comment]
Maybe the preview will be more easy
[data_preview.txt](https://github.com/1rosehip/jplist/files/943241/data_preview.txt)

**Comment by 1rosehip** [comment]
It seems that **count** property is missing. 
You can compare with response from here: http://jplist.com/datasourcesexamples/php-mysql-json-handlebars-demo

**Comment by renanarozen** [comment]
Hi
Thanks for your help!
Know i see the pagination but it does not do his work
I ask for 20 in each page so he show me 2 pages but when i move to the other page the items don't change

In your link i get your demo bur where it is written to sent the count property ?

Sorry I suppose i'm missing somthing

**Comment by renanarozen** [comment]
Buy the way It's seem if i'm not worng that in the demo from your link when i change the page the items not changing

**Comment by 1rosehip** [comment]
You are right, thank you for reporting this. In any case you can find the **count** code here https://github.com/1rosehip/jplist/blob/master/server/server-json.php in line 32

**Comment by renanarozen** [comment]
I't seem that when i i ask for 3 items in page the pagination vanished and when i change to 10 nothing is working

**Comment by 1rosehip** [comment]
The issue is fixed - please download https://github.com/1rosehip/jplist/blob/master/server/domain/pagination.php and recheck

**Comment by renanarozen** [comment]
Hi
I don't understand you fixed pagination.php file and i don't have it
From your example http://jplist.com/datasources/php-mysql-data-source => Usage Example all i need is to download js files like jplist.core-ajax.min.js etc... and not php files
Where i can find witch files i need and where to put them?

**Comment by 1rosehip** [comment]
It's not possible to implement server side php version without php :)

Please have a look at the php code located here: https://github.com/1rosehip/jplist/tree/master/server
Also php demo pages can be found here: https://github.com/1rosehip/jplist/tree/master/demo/php-mysql-demos

I'll update the download page accordingly so it will be more clear.
