### ISSUE TITLE
jPList Panel controls always bisible on small/medium screens

### ISSUE THREAD

**Issue by rBok6** [1rosehip/jplist#261]
Hi!

I'm using jplist on my website and I would like to have all panel controls always visible on small and medium screens. I don't like the ios button option for my website. 

Is there a way to do that?

You should include this information on your documentation. You don't explain how to use the ios button option and whether if it's optional or not.

And if it's optional you should explain how to make the panel controls always visible on small and medium screens.

Thanks.

**Comment by 1rosehip** [comment]
Please see the following issues:
https://github.com/1rosehip/jplist/issues/114
https://github.com/1rosehip/jplist/issues/97

**Comment by rBok6** [comment]
The second solution worked. Thanks!

**Comment by 1rosehip** [comment]
You are welcome
